### ISSUE TITLE
WMS_Mars Service End Point is not opening

### ISSUE THREAD

**Issue by tsmedley-kh06** [opengeospatial/geoedge-plugfest#13]
I have not seen this page so far this week, in the past, the link has taken me to the service.
![wms_mars connection issue](https://user-images.githubusercontent.com/9356702/39310270-f5f55536-4937-11e8-98df-141eebebcdc2.JPG)

**Comment by bermud** [comment]
Server is now available here:
http://mdms1-devel1.compusult.net/wes/GeopackageWMS/18?request=GetCapabilities
