### ISSUE TITLE
WMTS Oberon requires authentication to access

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/geoedge-plugfest#16]
Navigate to http://mdms1-devel1.compusult.net//wes/GeopackageWMTS/258/1.0.0/WMTSCapabilities.xml in the browser, which should show the WMTS capabilities of the server. Instead, this triggers the loading of a loging portal: http://mdms1-devel1.compusult.net/wes/portalLogin.jsp

**Comment by bermud** [comment]
It is now available here:
http://mdms1-devel1.compusult.net//wes/GeopackageWMTS/19/1.0.0/WMTSCapabilities.xml

**Comment by robinhoutmeyers** [comment]
The WMTS link still loads a portal requiring credentials input.

**Comment by bermud** [comment]
@robinhoutmeyers, you should use this  new link: https://wes-online.compusult.net/wes/GeopackageWMTS/665/1.0.0/WMTSCapabilities.xml
